version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: GraphQL_MySQL
    platform: linux/x86_64
    ports:
      - "3306:3306"
    # expose:
    #   - 3307
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/mysql_charset.cnf
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: udemydb
      MYSQL_USER: udemy_user
      MYSQL_PASSWORD: udemy_pass
      # MYSQL_TCP_PORT: 3307
