version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: postgres
    platform: linux/x86_64
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: udemydb
